# Generated by Django 3.0.5 on 2020-04-17 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20200417_0144'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='abb',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
