# Generated by Django 3.0.5 on 2020-04-20 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_size_abb'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='email',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
