# Generated by Django 3.0.5 on 2020-04-20 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0012_review_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='email',
            new_name='phone',
        ),
    ]
