# Generated by Django 3.0.5 on 2020-05-03 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20200421_0045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='product',
            name='sector',
            field=models.CharField(choices=[('kids', 'kids'), ('adults', 'adults'), ('accessories', 'accessories'), ('party planning', 'party planning'), ('decoration', 'decoration'), ('making', 'making')], default=' ', max_length=50),
        ),
        migrations.AddField(
            model_name='product',
            name='subsector',
            field=models.CharField(choices=[('Kids', (('boys', 'boy'), ('girl', 'girl'), ('baby', 'baby'))), ('Adults', (('men', 'men'), ('women', 'women'))), ('Accessories', (('toys', 'toys'), ('wigs', 'wigs'), ('hats', 'hats'), ('masks', 'masks'), ('decoration items', 'decoration items')))], default=' ', max_length=50),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('princess', 'princess'), ('heroes', 'heroes'), ('cartoons & animals', 'cartoons & animals'), ('holloween', 'holloween'), ('christmas', 'christmas'), ('jobs', 'jobs'), ('international', 'international'), ('Egyptian', 'Egyptian'), ('graduation', 'graduation'), ('cosplay', 'cosplay'), ('tv & movies', 'tv & movies'), ('fashion', 'fashion'), ('historical', 'historical')], default=' ', max_length=50),
        ),
    ]
