# Generated by Django 3.0.5 on 2020-05-04 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0016_auto_20200503_2316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Subcategory',
        ),
    ]
