# Generated by Django 3.0.5 on 2020-04-12 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wishlist_item',
            name='product',
        ),
        migrations.RemoveField(
            model_name='wishlist_item',
            name='wishlist',
        ),
        migrations.DeleteModel(
            name='Wishlist',
        ),
        migrations.DeleteModel(
            name='Wishlist_item',
        ),
    ]
